import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import * as schema from "./schema";
import { MockPool, MOCK_CENTRES, MOCK_REQUESTS, MOCK_ARTICLES, MOCK_DOCS } from "./mock";

const { Pool } = pg;

const hasRealDb = Boolean(
  process.env.DATABASE_URL &&
    !process.env.DATABASE_URL.startsWith('mock') &&
    !process.env.DATABASE_URL.startsWith('local'),
);

class HybridPool {
  private realPool: any = null;
  private mockPool: MockPool;

  constructor(connectionString?: string) {
    this.mockPool = new MockPool();
    if (connectionString) {
      try {
        this.realPool = new Pool({ connectionString });
      } catch (err) {
        console.warn('[DB] Failed to create pg.Pool. Using in-memory mock store.');
        this.realPool = null;
      }
    }
  }

  async query(text: string, params?: any[]) {
    if (this.realPool) {
      try {
        return await this.realPool.query(text, params);
      } catch (err: any) {
        console.warn(`[DB] PostgreSQL query failed (${err?.message || err}). Falling back to mock store for query:`, text.slice(0, 60));
        return await this.mockPool.query(text, params);
      }
    }
    return await this.mockPool.query(text, params);
  }

  on(event: string, handler: any) {
    if (this.realPool && typeof this.realPool.on === 'function') {
      this.realPool.on(event, handler);
    }
  }

  end() {
    return this.realPool?.end();
  }
}

let poolInstance: any;
let dbInstance: any;

if (hasRealDb) {
  poolInstance = new HybridPool(process.env.DATABASE_URL);
  try {
    const rawPool = new Pool({ connectionString: process.env.DATABASE_URL });
    dbInstance = drizzle(rawPool, { schema });
  } catch {
    dbInstance = null;
  }
} else {
  console.info('[DB] DATABASE_URL not set — running in local in-memory mock mode with Botswana healthcare seeds.');
  poolInstance = new HybridPool();
  dbInstance = null;
}

export const pool = poolInstance;
export const db = dbInstance;

export async function autoSeedDatabase() {
  try {
    // 1. Create tables if they don't exist
    await pool.query(`
      CREATE TABLE IF NOT EXISTS donation_centres (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        kind TEXT NOT NULL DEFAULT 'clinic',
        address TEXT,
        district TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        phone TEXT,
        is_open BOOLEAN NOT NULL DEFAULT TRUE,
        opens_at TIME,
        closes_at TIME,
        accepts_walk_ins BOOLEAN NOT NULL DEFAULT TRUE,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS donation_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        blood_type TEXT NOT NULL,
        priority TEXT NOT NULL DEFAULT 'planned',
        facility_name TEXT NOT NULL,
        description TEXT NOT NULL,
        district TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        response_count BIGINT NOT NULL DEFAULT 0,
        is_open BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        closed_at TIMESTAMPTZ
      );

      CREATE TABLE IF NOT EXISTS request_responses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_id BIGINT NOT NULL,
        clerk_user_id TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS health_articles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        body_markdown TEXT NOT NULL DEFAULT '',
        topic TEXT NOT NULL DEFAULT 'general',
        read_time_minutes BIGINT NOT NULL DEFAULT 5,
        icon_name TEXT NOT NULL DEFAULT 'heart',
        is_published BOOLEAN NOT NULL DEFAULT FALSE,
        published_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS donor_profiles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clerk_user_id TEXT NOT NULL UNIQUE,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        blood_type TEXT,
        district TEXT,
        phone TEXT,
        location_enabled BOOLEAN NOT NULL DEFAULT FALSE,
        verification_level INT NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS donor_documents (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clerk_user_id TEXT NOT NULL,
        document_type TEXT NOT NULL,
        document_url TEXT,
        object_path TEXT UNIQUE,
        status TEXT NOT NULL DEFAULT 'pending',
        reviewed_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS upload_grants (
        object_path TEXT PRIMARY KEY NOT NULL,
        clerk_user_id TEXT NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL,
        consumed_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS donor_donations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clerk_user_id TEXT NOT NULL,
        centre_id BIGINT,
        centre_name TEXT,
        donated_at TIMESTAMPTZ NOT NULL,
        verified BOOLEAN NOT NULL DEFAULT FALSE,
        verified_at TIMESTAMPTZ,
        tx_id TEXT,
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS feedback_responses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clerk_user_id TEXT,
        session_id TEXT,
        responses JSONB NOT NULL,
        app_version TEXT,
        platform TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS clinical_orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_number TEXT NOT NULL UNIQUE,
        idempotency_key TEXT UNIQUE,
        hospital_name TEXT NOT NULL,
        ward_room TEXT,
        doctor_clerk_user_id TEXT,
        patient_identifier TEXT,
        blood_type TEXT NOT NULL,
        component TEXT NOT NULL DEFAULT 'prbc',
        units_requested INT NOT NULL DEFAULT 1,
        urgency TEXT NOT NULL DEFAULT 'elective',
        indication TEXT,
        status TEXT NOT NULL DEFAULT 'pending',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS transfusion_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT,
        idempotency_key TEXT UNIQUE,
        unit_barcode TEXT NOT NULL,
        patient_identifier TEXT NOT NULL,
        clinician_clerk_user_id TEXT NOT NULL,
        verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        started_at TIMESTAMPTZ,
        completed_at TIMESTAMPTZ,
        has_reaction BOOLEAN NOT NULL DEFAULT FALSE,
        reaction_details JSONB,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS blood_units (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bag_barcode TEXT NOT NULL UNIQUE,
        donation_tx_id TEXT,
        donor_hash TEXT NOT NULL,
        blood_type TEXT NOT NULL,
        component_type TEXT NOT NULL DEFAULT 'whole_blood',
        volume_ml DOUBLE PRECISION NOT NULL DEFAULT 450,
        status TEXT NOT NULL DEFAULT 'quarantined',
        vault_location TEXT,
        is_reactive BOOLEAN NOT NULL DEFAULT FALSE,
        viral_markers JSONB,
        tested_by_clerk_user_id TEXT,
        collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        expires_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS transit_manifests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        manifest_number TEXT NOT NULL UNIQUE,
        idempotency_key TEXT UNIQUE,
        origin_facility TEXT NOT NULL,
        destination_facility TEXT NOT NULL,
        courier_clerk_user_id TEXT,
        driver_name TEXT NOT NULL DEFAULT 'Dispatch Driver',
        status TEXT NOT NULL DEFAULT 'assigned',
        unit_barcodes JSONB NOT NULL DEFAULT '[]'::jsonb,
        cooler_box_id TEXT,
        departed_at TIMESTAMPTZ,
        delivered_at TIMESTAMPTZ,
        recipient_signature TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS transit_telemetry (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        manifest_id BIGINT NOT NULL,
        event_id TEXT UNIQUE,
        temperature_celsius DOUBLE PRECISION NOT NULL,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        is_alert_triggered TEXT,
        logged_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      -- Apply non-destructive column alignments
      ALTER TABLE donor_documents ADD COLUMN IF NOT EXISTS object_path TEXT;
      ALTER TABLE donor_documents ADD COLUMN IF NOT EXISTS document_url TEXT;
      ALTER TABLE donor_donations ADD COLUMN IF NOT EXISTS tx_id TEXT;
      ALTER TABLE clinical_orders ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
      ALTER TABLE transfusion_logs ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
      ALTER TABLE transit_manifests ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
      ALTER TABLE transit_telemetry ADD COLUMN IF NOT EXISTS event_id TEXT;
    `);



    console.info('[DB] Database schema verified and clean.');
  } catch (err: any) {
    console.warn('[DB] Auto-seed schema error (non-fatal):', err?.message || err);
  }
}

export async function purgeAllMockData() {
  console.info('[DB] Ensuring database schema exists...');
  await autoSeedDatabase();

  console.info('[DB] Purging all data across tables...');
  await pool.query(`
    TRUNCATE TABLE 
      donation_requests, 
      request_responses, 
      health_articles,
      donor_profiles,
      donor_documents, 
      upload_grants,
      donor_donations,
      feedback_responses,
      clinical_orders, 
      transfusion_logs, 
      blood_units, 
      transit_manifests, 
      transit_telemetry,
      donation_centres
    RESTART IDENTITY CASCADE;
  `);
  console.info('[DB] Database purge complete. All tables clean.');
}

export * from "./schema";
export * from "./mock";


