import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import * as schema from "./schema";
import { MockPool, MOCK_CENTRES, MOCK_REQUESTS, MOCK_ARTICLES, MOCK_DOCS } from "./mock";

const { Pool } = pg;

const hasRealDb = Boolean(
  process.env.DATABASE_URL &&
    !process.env.DATABASE_URL.startsWith('mock') &&
    !process.env.DATABASE_URL.startsWith('local'),
);

class HybridPool {
  private realPool: any = null;
  private mockPool: MockPool;

  constructor(connectionString?: string) {
    this.mockPool = new MockPool();
    if (connectionString) {
      try {
        this.realPool = new Pool({ connectionString });
      } catch (err) {
        console.warn('[DB] Failed to create pg.Pool. Using in-memory mock store.');
        this.realPool = null;
      }
    }
  }

  async query(text: string, params?: any[]) {
    if (this.realPool) {
      try {
        return await this.realPool.query(text, params);
      } catch (err: any) {
        console.warn(`[DB] PostgreSQL query failed (${err?.message || err}). Falling back to mock store for query:`, text.slice(0, 60));
        return await this.mockPool.query(text, params);
      }
    }
    return await this.mockPool.query(text, params);
  }

  on(event: string, handler: any) {
    if (this.realPool && typeof this.realPool.on === 'function') {
      this.realPool.on(event, handler);
    }
  }

  end() {
    return this.realPool?.end();
  }
}

let poolInstance: any;
let dbInstance: any;

if (hasRealDb) {
  poolInstance = new HybridPool(process.env.DATABASE_URL);
  try {
    const rawPool = new Pool({ connectionString: process.env.DATABASE_URL });
    dbInstance = drizzle(rawPool, { schema });
  } catch {
    dbInstance = null;
  }
} else {
  console.info('[DB] DATABASE_URL not set — running in local in-memory mock mode with Botswana healthcare seeds.');
  poolInstance = new HybridPool();
  dbInstance = null;
}

export const pool = poolInstance;
export const db = dbInstance;

export async function autoSeedDatabase() {
  try {
    // 1. Create tables if they don't exist
    await pool.query(`
      CREATE TABLE IF NOT EXISTS donation_centres (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        kind TEXT NOT NULL DEFAULT 'clinic',
        address TEXT,
        district TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        phone TEXT,
        is_open BOOLEAN NOT NULL DEFAULT TRUE,
        opens_at TIME,
        closes_at TIME,
        accepts_walk_ins BOOLEAN NOT NULL DEFAULT TRUE,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS donation_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        blood_type TEXT NOT NULL,
        priority TEXT NOT NULL DEFAULT 'planned',
        facility_name TEXT NOT NULL,
        description TEXT NOT NULL,
        district TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        response_count BIGINT NOT NULL DEFAULT 0,
        is_open BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        closed_at TIMESTAMPTZ
      );

      CREATE TABLE IF NOT EXISTS request_responses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_id BIGINT NOT NULL,
        clerk_user_id TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS health_articles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        slug TEXT NOT NULL UNIQUE,
        body_markdown TEXT NOT NULL DEFAULT '',
        topic TEXT NOT NULL DEFAULT 'general',
        read_time_minutes BIGINT NOT NULL DEFAULT 5,
        icon_name TEXT NOT NULL DEFAULT 'heart',
        is_published BOOLEAN NOT NULL DEFAULT FALSE,
        published_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS donor_profiles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clerk_user_id TEXT NOT NULL UNIQUE,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        blood_type TEXT,
        district TEXT,
        phone TEXT,
        location_enabled BOOLEAN NOT NULL DEFAULT FALSE,
        verification_level INT NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS donor_documents (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clerk_user_id TEXT NOT NULL,
        document_type TEXT NOT NULL,
        document_url TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        reviewed_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS feedback_responses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        clerk_user_id TEXT,
        session_id TEXT,
        responses JSONB NOT NULL,
        app_version TEXT,
        platform TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS clinical_orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_number TEXT NOT NULL UNIQUE,
        hospital_name TEXT NOT NULL,
        ward_room TEXT,
        doctor_clerk_user_id TEXT,
        patient_identifier TEXT,
        blood_type TEXT NOT NULL,
        component TEXT NOT NULL DEFAULT 'prbc',
        units_requested INT NOT NULL DEFAULT 1,
        urgency TEXT NOT NULL DEFAULT 'elective',
        indication TEXT,
        status TEXT NOT NULL DEFAULT 'pending',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    // 2. Check if donation_centres is empty; if so, seed from MOCK_CENTRES
    const centresRes = await pool.query('SELECT COUNT(*) FROM donation_centres');
    if (Number(centresRes.rows[0]?.count ?? 0) === 0) {
      console.log('[DB] Seeding default Botswana donation centres...');
      for (const c of MOCK_CENTRES) {
        await pool.query(
          `INSERT INTO donation_centres (name, kind, address, district, latitude, longitude, phone, is_open, opens_at, closes_at, accepts_walk_ins, is_active)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
          [c.name, c.kind, c.address, c.district, c.latitude, c.longitude, c.phone, c.is_open, c.opens_at, c.closes_at, c.accepts_walk_ins, c.is_active]
        );
      }
    }

    // 3. Check if donation_requests is empty; if so, seed from MOCK_REQUESTS
    const requestsRes = await pool.query('SELECT COUNT(*) FROM donation_requests');
    if (Number(requestsRes.rows[0]?.count ?? 0) === 0) {
      console.log('[DB] Seeding default Botswana emergency donation requests...');
      for (const r of MOCK_REQUESTS) {
        await pool.query(
          `INSERT INTO donation_requests (blood_type, priority, facility_name, description, district, latitude, longitude, response_count, is_open)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
          [r.blood_type, r.priority, r.facility_name, r.description, r.district, r.latitude, r.longitude, r.response_count, r.is_open]
        );
      }
    }

    // 4. Check if health_articles is empty; if so, seed from MOCK_ARTICLES
    const articlesRes = await pool.query('SELECT COUNT(*) FROM health_articles WHERE is_published = true');
    if (Number(articlesRes.rows[0]?.count ?? 0) === 0) {
      console.log('[DB] Seeding default health articles...');
      for (const a of MOCK_ARTICLES) {
        await pool.query(
          `INSERT INTO health_articles (title, slug, body_markdown, topic, read_time_minutes, icon_name, is_published, published_at)
           VALUES ($1, $2, $3, $4, $5, $6, true, NOW())
           ON CONFLICT (slug) DO UPDATE SET is_published = true, published_at = COALESCE(health_articles.published_at, NOW())`,
          [a.title, a.slug, a.body_markdown, a.topic, a.read_time_minutes, a.icon_name]
        );
      }
    }

    // 5. Check if donor_documents is empty; if so, seed from MOCK_DOCS
    const docsRes = await pool.query('SELECT COUNT(*) FROM donor_documents');
    if (Number(docsRes.rows[0]?.count ?? 0) === 0) {
      console.log('[DB] Seeding sample verification queue documents...');
      for (const d of MOCK_DOCS) {
        await pool.query(
          `INSERT INTO donor_documents (clerk_user_id, document_type, document_url, status)
           VALUES ($1, $2, $3, $4)`,
          [d.clerk_user_id, d.document_type, d.document_url, d.status]
        );
      }
    }

    // 6. Check if donor_profiles is empty; if so, seed baseline demo donor profiles
    const donorsRes = await pool.query('SELECT COUNT(*) FROM donor_profiles');
    if (Number(donorsRes.rows[0]?.count ?? 0) === 0) {
      console.log('[DB] Seeding baseline donor profiles...');
      await pool.query(`
        INSERT INTO donor_profiles (clerk_user_id, first_name, last_name, blood_type, district, phone, location_enabled, verification_level)
        VALUES 
          ('user_donor_001', 'Kabo', 'Tau', 'O-', 'Gaborone', '+267 71 234 567', true, 1),
          ('user_donor_002', 'Lesego', 'Moloi', 'A+', 'Francistown', '+267 72 345 678', true, 1),
          ('user_donor_003', 'Tshepo', 'Dube', 'B+', 'Maun', '+267 73 456 789', true, 2),
          ('user_donor_004', 'Neo', 'Kgosi', 'O+', 'Serowe', '+267 74 567 890', true, 4),
          ('user_donor_005', 'Amantle', 'Montsho', 'AB-', 'Kanye', '+267 75 678 901', true, 3)
        ON CONFLICT (clerk_user_id) DO NOTHING
      `);
    }
  } catch (err: any) {
    console.warn('[DB] Auto-seed error (non-fatal):', err?.message || err);
  }
}

export * from "./schema";
export * from "./mock";


